compile/DLL/makefile
compile/DYLIB/makefile
compile/SO/makefile
source/Body.cpp
source/Line.cpp
source/Misc.cpp
source/Misc.h
source/MoorDyn.cpp
source/Rod.cpp
test/Mooring/BodiesAndRods.dat
test/bodies_and_rods.cpp
test/minimal.cpp
test/quasi_static_chain.cpp

Added a test with bodies and rods. I BTW fixed some memory errors associated with the Rods

Test bodies and rods

---

.github/workflows/build-test.yml

Upgraded delete-tag-and-release github action

---

.github/workflows/build-test.yml

Apparently the new version of the action fails if there is no such a tag

---

source/Body.cpp
source/Body.hpp
source/Connection.cpp
source/Connection.hpp
source/Line.cpp
source/Line.hpp
source/Rod.cpp
source/Rod.hpp
source/Waves.cpp
source/Waves.hpp

Remove the extra WavesRef typedefs

---

source/Line.cpp
source/Line.hpp

I also accidentally fixed a bug

Allow using non linear bending stiffness

---

docs/angles.svg
docs/structure.rst
source/Line.cpp
source/Misc.cpp
source/Misc.hpp
source/MoorDyn2.cpp
source/Rod.cpp
source/Rod.hpp
source/Time.hpp
tests/CMakeLists.txt
tests/Mooring/BeamCantilevered.txt
tests/Mooring/BeamSimplySupported.txt
tests/Mooring/RodHanging.txt
tests/Mooring/RodPinnedFloating.txt
tests/beam.cpp
tests/rods.cpp

Just to let you know that I am working on fixing rods, so @mattEhall do not waste your time on them

Fixes for rods

---

source/MoorDyn2.cpp

Apparently <limits> is also required

Fix windows compilation

---

source/Connection.hpp
source/Line.cpp
source/MoorDyn2.cpp
source/Time.cpp
source/Time.hpp

Reading output options fix, rk2 fix, catenary line profile initialization fix, added simulation time to connection object for debugging purposes, and tangential Froude-Krylov force calculation fix.

Minor bug fixes from Ryan

---

docs/conf.py
docs/coupling.rst
docs/starting.rst
docs/structure.rst

Documentation improvements

---

docs/structure.rst

Some lists on the docs were not working

Fixed some lists

---

source/Rod.cpp

Here is the VOF0 revert and the moment of inertia correction from @AlexWKinley as discussed in PR #97

VOF0 revert, inertia correction

---

.github/workflows/build-mingw.yml
.github/workflows/build-test.yml
tests/CMakeLists.txt

I enabled testing on all platforms (Linux, Windows and MacOS). The price is thought I have been enforced to drop intel Fortran compiler.
Fortran compilation is anyway tested on Linux and Windows (MinGW)

Testing on all platforms

---

.github/workflows/build-test.yml
.github/workflows/check-version.yml
.github/workflows/python-wheels.yml
wrappers/python/wheels.github/set_eigen_data.py
wrappers/python/wheels.github/setup.py

It seems the releases are now correctly named, after checking the version during the PR
Now I need to prepare auto-uploading python packages (In my fork)

Automated releases

---

.github/workflows/build-test.yml
.github/workflows/python-wheels-manylinux-arch.yml
.github/workflows/python-wheels.yml

Alright! This is finally working!
https://test.pypi.org/project/moordyn/2.2.2/#files
I excluded, for the time being, the musllinux platforms, which is popular just on embedded devices. They can anyway install moordyn using the sdist, so they are actually supported by the same pip command

Manylinux Python wheels

---

docs/compiling.rst
docs/drivers.rst
docs/inputs.rst
docs/structure.rst
source/Body.hpp

These updates hopefully help clear up some confusion seen in issues and messages I have received about using the step function.

Clarifies some parts of the documentation

---

README.md
docs/compiling.rst
docs/drivers.rst
docs/inputs.rst
docs/structure.rst
docs/troubleshooting.rst

Some minor updates and clarifications for the documentation. Includes formatting input files better and input file changes for MD-F in OpenFAST v4

Pinned bodies docs update and refresh

---

docs/inputs.rst

Docs update for MDF new feature: line failures

Docs update for failure

---

docs/compiling.rst

AUR package documentation

---

docs/inputs.rst

Updated docs for viscoelastic work on the MD_F side.

WIP: Updated MDF visco docs

---

wrappers/python/moordyn/moordyn.py

fix(python): The sea bed force was actually returning the Froude-Krilov one

---

source/MoorDyn2.cpp

fix(core): Water depth warning was printed no matter whether it was corrected or not

---

source/MoorDyn2.hpp

Stiffness file reading correction

---

cmake/FindRust.cmake

FindRust.cmake is failing, see https://github.com/FloatingArrayDesign/MoorDyn/pull/291
This is just updating FindRust.cmake with the last version on https://github.com/corrosion-rs/corrosion . Hopefully that is fixing the issue

fix(build): Upgraded the FindRust.cmake
