FloatingArrayDesign/MoorDyn

.github/workflows/build-test.yml
I have no rights to create releases, so I drop v2 from the nightly autogeneration
=> Drop v2 branch from the nightly packages generation

source/Line.cpp
The typo was actually irrelevant, since on the abscence of points getNonlinearE() is never called
=> getNonlinearE() shall return E instead of EI when no points

bench/MDBench.hpp, bench/WaveBench.hpp, source/Body.cpp, source/Body.hpp, source/Connection.hpp, source/Line.hpp, source/Misc.cpp, source/Misc.hpp, source/MoorDyn2.cpp, source/MoorDyn2.hpp, source/Rod.cpp, source/Rod.hpp, source/Seafloor.cpp, source/Seafloor.hpp, source/Waves.cpp, source/Waves.hpp, source/Waves/WaveGrid.cpp, source/Waves/WaveGrid.hpp, tests/CMakeLists.txt, tests/testDecomposeString.cpp, tests/wave_surface.cpp, tests/wavekin_7.cpp
The main thing this commit does is get rid of a lot of the usage of char arrays and replace it with c++ strings. This means that decomposeString can handle inputs and outputs on length larger than 10, and also avoids a lot of raw string copies that are both dangerous and cause some compilers to produce warnings. A new test has been added that compares the output of the new decomposeString function with the old implementation to try and make sure they match.
A few errant bugs have been fixed, and a little work has been done to try and improve compile times. Mainly moving the step of solving a 6x6 system of equations into it's own single function in Misc.cpp prevents Body.cpp and Rod.cpp from each compiling the same code twice, and that code specifically takes a while to compile. I've also …
=> Improve decomposeString and fix other various bugs and warnings

source/MoorDyn2.cpp
In our last PR a `entires[1]` got changed to an `entries[2]`, when trying to read the attachment for Bodies. This PR just fixes that bug.
=> Fix reading incorrect entry for Body attachment

wrappers/python/.github.setup.py
The source files on the subfolders are not considered on the wheels autobuilding tool
=> Fix missing source files when setting up the wheels

source/Body.cpp, source/Body.hpp, source/Connection.cpp, source/Connection.hpp, source/Line.cpp, source/Misc.cpp, source/Misc.hpp, source/MoorDyn2.cpp, source/MoorDyn2.hpp, source/Rod.cpp, source/Rod.hpp, source/Time.cpp
These changes fix a few bugs that existed with rod dynamics, in particular for free rods. The biggest issue was the rod Mass matrix was double counting the node masses. Other issues involved horizontal rods rotating when sinking/falling. They have been verified against MoorDynF and analytical solutions. 
The other set of changes is output flag standardization with MoorDynF. This is in conjunction with an update to MoorDynF that will come soon, and it makes it so both versions accept the same output flags and produce the same output results. Much of it was to bring this version up to date with what the documentation says it can do, and then there are some added features. These changes have also been verified with the changes in MoorDynF for all of the output channels.
=> Rod dynamics and outputs updates

source/Point.cpp
Some variables at the points were never initialized, which might trigger floating point exception signals when serializing. This is not a big deal usually, but it is for instance crashing the OpenFOAM simulations since OpenFOAM has a catcher for those.
I am merging right away. This PR is just to keep a record.
=> Avoid floating-point exception signals when serializing

.github/workflows/python-wheels.yml, CMakeLists.txt, wrappers/python/.github.setup.cfg, wrappers/python/CMakeLists.txt, wrappers/python/pyproject.toml.in, wrappers/python/setup.py.in, wrappers/python/wheels.github/pyproject.toml, wrappers/python/wheels.github/set_eigen_data.py, wrappers/python/wheels.github/set_version.py, wrappers/python/wheels.github/setup.py
setup.py based python crafting is finally deprecated, so i moved to pyproyect.toml. It seems to work fine:
https://github.com/core-marine-dev/MoorDyn/actions/runs/5667130409
I am merging right away
=> setup.py deprecated

source/Body.cpp, source/Body.hpp, source/Line.cpp, source/Line.hpp, source/Misc.cpp, source/Misc.hpp, source/MoorDyn2.cpp, source/Point.cpp, source/Point.hpp, source/Rod.cpp, source/Rod.hpp
Resolves a body added mass bug, a rod Aq bug, rod inertia bug, and a translateMass bug:
The following three bugs have been fixed in the fortran code and are being implemented in a PR soon.
1. The body added mass calculation was adding a volume to the mass, which is dimensionally incorrect, and was missing the water density and the Ca coefficient. To resolve this, the env variable needed to be loaded in the setup function rather than a separate function. To ensure continuity across the objects, I made the setEnv function setWaves (an inline function) and the env variable is now set in the setup function for each object.
2. The rod Aq bug was identified by others at NREL who work on the fortran side. The force labeled Froude-Krylov force is actually the long-wave diffraction force. The …
=> Body and rod bug fixes

source/Line.cpp, source/Waves.cpp, source/Waves/SpectrumKin.cpp
When lines compute the fluid inertia forces, they didn't include segment submergence in the calculation. It's possible that the code as written expects the volume array to take that into account, which does not currently happen. If you look at the section that computes the mass matrix for each node, it includes a correction for submergence along with the volume array. If we want to rewrite these so that the volume array is actually submerged volume, that's definitely possible. I don't know if there's an advantage one way or the other. 
Additionally in the code for wavekin 7, which sums up component waves at all the nodes, there was a missing minus sign for the z component of the water acceleration. It looks like this issue is specific to this wave mode, it is not present in wave mode 2, …
=> Bug fix for line fluid inertia forces, and Wavekin 7 Ud_z

README.md, docs/compiling.rst, docs/conf.py, docs/drivers.rst, docs/inputs.rst, docs/structure.rst, docs/waterkinematics.rst, source/MoorDyn2.cpp
Some more updates to the docs, mostly typos fixes.  A few improvements to compiling instructions based on user feedback. 
@sanguinariojoe was wondering if you could help with a couple docs things:
First, the doxygen function references are not working anymore. I don't think I changed anything but they no longer link. Compare the water kinematics section from [your docs](https://moordyn.readthedocs.io/en/master/waterkinematics.html) and the new [dev docs](https://moordyn.readthedocs.io/en/latest/waterkinematics.html). Could it be a setting on readthedocs that we need to change?
When I compile the docs locally I get the following function errors: 
```
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets …
```
=> More Docs Improvements

docs/compiling.rst, docs/drivers.rst, docs/inputs.rst, docs/theory.rst
Merging and closing, just typos in the docs that I missed.
=> Fixing typos, correction to python install instructions

CMakeLists.txt, docs/compiling.rst, source/Line.cpp, source/Line.hpp, source/MoorDyn2.cpp, source/QSlines.hpp, source/Rod.cpp, tests/beam.cpp, tests/pendulum.cpp, tests/rods.cpp, tests/seafloor.cpp, tests/wavekin.cpp, wrappers/python/pyproject.toml.in, wrappers/python/wheels.github/pyproject.toml
Some minor bug fixes to be added before the MoorDyn release:
1. Fixed typos across a number of areas, including references to the documentation
2. Fixed an error that prevented outputs from being written when writelog flag was disabled
3. Added a missing axial drag coefficient that was also added to MoorDynF discussed in OpenFAST/openfast#1727
4. Made the internal Eigen the default flag for compiling
5. Fixed the catenary solver and added support for anchors and fairleads reversed
=> Updates from dev before new version release

source/Body.cpp
Prior to this body rotations, called by the BODY#RX/Y/Z flag, were outputting the body rotation in radians. The standard I/O units should all be degrees.
=> Body output units bug fix

docs/drivers.rst, source/Body.cpp, source/MoorDyn2.cpp, source/MoorDyn2.hpp
Resolves an issue where fixed bodies only initialized at 0,0,0,0,0,0 irregardless of what was specified in the input file. This was due to fixed bodies not initializing, and so default values were used.
=> Fixes initialization location of fixed bodies

source/Line.hpp, source/MoorDyn2.cpp, source/Rod.hpp, tests/pendulum.cpp
Resolves #160 
This PR removes the double counting of line weight and changes the dynamic relaxation routine to match the now fixed fortran code. The changes to the dynamic relaxation routine are as follows:
- The user inputted dtIC is subdivided into 10 steps, with the intent that the dtIC is the time that the user wants to see stability over for convergence
- Changes number of convergence iterations so that 9 iterations are compared to the current fairten (because of subdividing each dtIC into 10 pieces)
- Changes the while loop parameter to a tolerance (this can be adjusted, just seemed like the easiest method) which eliminates an extra timestep being run when convergence is not reached. Prior to this, the final time after the loop would be ICTmax+dtIC, now it is just ICTmax
- Changed …
=> Adjustments to Dynamic relaxation

source/Misc.hpp, source/MoorDyn2.cpp, tests/bodies.cpp
Based on discussion in #163 
Adds canonical Euler angles function from Eigen to replace the Euler angle function. This resolves an issue where outputted roll could not be negative, and where certain input body rotations would not be reflected in the output rotation values. This only changes the values written to output files, not internal dynamics. 
Below are outputs before and after the change for a coupled body rotating periodically.
Before:
After:
@AlexWKinley thanks for putting together the suggested code for this, I only had to make some minor changes. 
We can move this into Misc.cpp if we feel it goes better there. I put it where it is because that's where the Quat2Euler functions are.
=> Added canonical Euler angles for outputs

docs/inputs.rst, source/Body.cpp, source/Body.hpp, source/Line.hpp, source/Misc.hpp, source/MoorDyn2.cpp, source/MoorDyn2.hpp, source/Rod.cpp, source/Rod.hpp, source/Time.cpp, source/Time.hpp, tests/Mooring/body_tests/pinnedBody.txt, tests/bodies.cpp
Successfully updated rebase so now it should avoid duplicates with dev branch.
**Original commit message from #178:**
This PR includes a new option for bodies, allowing them to behave as a pinned object. It contains a corresponding unit test and documentation updates. It also contains a feature update that prints time steps to the terminal while running, similar to how MDF works at runtime.
The formulation follows the pinned rods orientation closely. Inertial responses and forces have been added to the getStateDeriv and getFnet functions for both bodies and rods. The torque from translational acceleration is:
F_iner [4:6] = M.bottomLeftCorner * a6[1:3]
and the inertial response force to acceleration is given as (contains two terms to avoid counting the externally applied force): …
=> Pinned bodies added

.github/dependabot.yml
Dependabot is constantly opening PRs against master, but on our developing system those shall be added to dev instead
=> Point the dependabot against dev branch

.github/workflows/check-version.yml
To replace https://github.com/FloatingArrayDesign/MoorDyn/pull/187, which has conflicts
=> mukunku/tag-exists-action from 1.5.0 to 1.6.0

source/MoorDyn2.cpp
Even though the issue was closed,  @anjaschnepf made a point there. Lines can be defined without points, so we shall not trigger an error
=> Fixes #196

docs/inputs.rst, source/Body.cpp, tests/Mooring/body_tests/bodyDrag.txt, tests/bodies.cpp
fixes #205 and closes #206.
Fixes the way that drag coefficients are handled so that the viscous drag force follows the following formula: 
```math
F \\
=
0.5 * \rho_w * \\
OrMat\\
\begin{bmatrix}
CdA_x & 0 & 0 \\
0 & CdA_y & 0 \\
0 & 0 & CdA_z  \\
\end{bmatrix}
OrMat^T *\\
(\vec v_i  * \\
|\vec v_i |)
```
The same equation is applied for the rotational drag coefficients.
=> Update to body drag coefficients 

source/Body.cpp, tests/Mooring/body_tests/bodyDrag.txt, tests/bodies.cpp
fixes #205 
I think this should be a sufficient change to address the issue of getting negative drag coefficients in certain orientations.
The new body test fails without this change because its z drag coefficient is negative, causing the body to fly off the infinity. With the fix the test passes normally. Once others are happy with this change, I'll fix the merge conflict.
=> Prevent body drag coeffs from being negative

source/Body.cpp
See conversation in #208. Fixing a minor bug in how velocities are multiplied for body drag coefficients. 
@AlexWKinley does this look like what you had in mind?
=> Minor fix in velocities for body drag calc

source/Body.cpp, source/Line.cpp, source/Line.h, source/Line.hpp, source/Misc.cpp, source/Misc.hpp, source/Point.cpp, source/Waves.cpp, source/Waves.hpp, tests/CMakeLists.txt, tests/beam.cpp, tests/conveying_fluid.cpp, wrappers/fortran/MoorDyn.f90, wrappers/matlab/MoorDynM_IsLinePressBend.cpp, wrappers/matlab/MoorDynM_SetLinePressBend.cpp, wrappers/matlab/MoorDynM_SetLinePressInt.cpp, wrappers/python/cmoordyn.cpp, wrappers/python/moordyn/moordyn.py
This effect would be important for pipes, like risers, due to both the external pressure and the internal flow.
Some notes:
- It is disable by default, so it is harmless.
- It is not controllable from the config file, just from the API.
- To enable it the C API function MoorDyn_SetLinePressBend() shall be called
- Internal flow pressure can be set with the C API entry MoorDyn_SetLinePressInt()
- ~The wrappers are not ready yet. I hope I will have them ready today or tomorrow~
=> Bending due to pressure forces

README.md, docs/compiling.rst, docs/conf.py, docs/drivers.rst, docs/index.rst, docs/inputs.rst, docs/theory.rst, docs/waterkinematics.rst, source/MoorDyn2.cpp
Fixed typos found and/or reported by users. Aims to clear up common questions seen on OepnFAST help pages. Updates the FAST.Farm example to be consistent with current capabilities. Adds more references to publications about feature improvements.
=> Docs update: typos, more references, and updated FF file

compile/DLL/makefile, compile/DYLIB/makefile, compile/SO/makefile
Fixes the regression introduced on #225, which made impossible to compile with the legacy makefiles
@RyanDavies19 , please test it on your Mac and eventually merge. On the other hand, at some point we should address your problems with CMake
=> Get the MoorDyn version on the legacy compilation systems

source/Body.cpp, source/Body.hpp, source/Misc.hpp, source/MoorDyn2.cpp, source/Point.cpp, source/Point.hpp, source/Rod.cpp, source/Rod.hpp, tests/CMakeLists.txt, tests/Mooring/body_tests/floatingBodies.txt, tests/Mooring/body_tests/orbitalBody.txt, tests/bodies.cpp
=> Fixes #207 

source/Rod.cpp, source/Rod.hpp
Changed the rod submergence code to match what is in MD-F, which has been verified with other codes. The submergence scalar, VOF0, was being incorrectly calculating causing rods to have less buoyancy than they should. Both MD-F and MD-C now match on the heave decay test for the case in #236. 
Resolves #236
=> Fixed rod hydrostatics bug

.github/workflows/build-test.yml, .github/workflows/python-wheels-emulated.yml, .github/workflows/python-wheels-test.yml, .github/workflows/python-wheels.yml, .github/workflows/python-wrapper.yml
I fixed a lot of problems on the Python wrappers, and made them more flexible.
The next step is getting VTK linked dynamically instead of statically.
New supported architectures:
- MacOS (>=10.15) arm64 (x86_64 was compiled, but I doubt it properly worked)
- MUSLLinux
Lost architectures:
- PyPy (>3.7)
=> Better Python wrappers

wrappers/python/setup.py.in
=> fix(python): Absolute paths are not accepted any longer

wrappers/fortran/MoorDyn.f90, wrappers/matlab/MoorDynM_Deserialize.cpp, wrappers/matlab/MoorDynM_GetCFL.cpp, wrappers/matlab/MoorDynM_GetDt.cpp, wrappers/matlab/MoorDynM_GetTimeScheme.cpp, wrappers/matlab/MoorDynM_Serialize.cpp, wrappers/matlab/MoorDynM_SetCFL.cpp, wrappers/matlab/MoorDynM_SetDt.cpp, wrappers/matlab/MoorDynM_SetTimeScheme.cpp, wrappers/python/cmoordyn.cpp, wrappers/python/moordyn/moordyn.py
Just a couple of API entries that were missing on the wrappers. Notes:
- I compiled Python and Fortran. Can anybody try to compile the matlab one?
- I did not check any of them (related: https://github.com/FloatingArrayDesign/MoorDyn/issues/203)
=> Missing API entries on the wrappers

.github/workflows/matlab.yml
A GitHUB action to compile the MATLAB mex files and run a small test. Notes:
- It is quite shitty because it can not be integrated with CMake
- I tried to make it work on Windows, but it gives an error with little to none useful information to fix it.
- At some point it would be great to have a common framework to create and run the tests with both GitHUB actions and CMake
=> MATLAB wrapper testing

source/Seafloor.cpp, source/Waves.cpp, source/Waves/WaveGrid.cpp
This fixes a path error raised when running the MATLAB wrapper (seen in #274)
=> fix: fixed path errors in waves files.

wrappers/python/moordyn/moordyn.py
=> fix(python): The time is not required on moordyn.GetWavesKin() anymore

docs/inputs.rst, docs/references.rst, docs/troubleshooting.rst
Docs update for new MoorDyn-F external loads feature.
=> docs: Updated docs for OpenFAST/openfast#2597

source/MoorDyn.cpp, source/MoorDyn.h, source/MoorDyn2.cpp, source/MoorDyn2.hpp
This adds a dummy AllOutput function to the old API wrapper that prints a message stating "In version 2, AllOutput is automatically called by MoorDynStep". This reduces warning messages when using the old API. This was seen when updating the WECSim libraries in https://github.com/WEC-Sim/MoorDyn/pull/7. 
@sanguinariojoe, let me know if there is a better way to print the message here. I didn't see anything in the C header files that allowed for the use of LOGMSG.
=> fix: added dummy AllOutput to old API

.github/workflows/build-test.yml, tests/CMakeLists.txt, tests/Cargo.toml, tests/rust_minimal.rs, wrappers/rust/CMakeLists.txt, wrappers/rust/Cargo.toml
It is quite ugly, but I do not know if it is worthy to create a thin wrapper to make it easier to use... Probably not...
=> First Rust test!

docs/inputs.rst, source/Line.cpp, source/Misc.hpp, source/MoorDyn2.cpp, source/Rod.cpp
Test 14 math_tests failed
**Feature or improvement description**
Setting submergence calculation change (VOF0) to be more in line with how openfast moordyn sets VOF0.
Added more outputs for rods in the input file for additional analysis of data to compare with fortran version: 
Weight (W)
buoyancy (Bo)
Bottom contact force (B)
Tangential drag forces (Ap)
Axial fluid inertia force (Aq)
Transverse drag forces (Dp)
Tangential drag forces (Dq)
**Related issue, if one exists**
**Impacted areas of the software**
MoorDyn
**Additional supporting information**
**Test results, if applicable**
<!-- Release checklist:
=> Setting submergence equation change to fortran logic and added additional rod outputs for the input file
